### ISSUE TITLE
Contact Form Integration

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#105]

**Comment by ZiggyAtl** [comment]
Please can you alter the title of the page (and where it appears in the navigation) to Contact Us

Is the font you used the same as the standard one used on the other pages?

Please can you modify it to look something like this one https://www.infinitegiving.com/company/contact  that includes adding the wording about responding within 24 hours (want to set expectation with user). The boxes are also not as wide which is good, as the ones on our site currently auto expand to the width of the page, and therefore look far too wide for the info that needs to go in there.

I don't want the suggestion text they have in each box.

Instead of where it says Organization, please can the box say 'Subject' and then have a drop down menu with;
Feedback & General Questions  [which would send the form to hello@comission.art]
Technical & Account Support  [which would send the form to support@comission.art
Become a partner Museum or Artist  [which would send the form to partner@comission.art]

thanks

**Comment by jonathanwburr** [comment]
@jennyvanderheiden could you take a pass for design at Bills feedback for the form page design? Let me know if you want to chat any of it through

**Comment by jonathanwburr** [comment]
@ZiggyAtl a couple of technical questions:

1. Do you want the subject dropdown field to be required ( a user must make a selection in order to submit the form)?
2. If we don't make the subject field required, which email address would you like submissions to go to?
3. Do you want to use the copy from example form verbatim, 'We'd love to hear from you. Just send us a message, and we'll respond within 24 hours.' and if not could you provide specific language.
4. Could you provide copy to show a user when the form is submitted. Example: 'Thanks for getting in touch, we have received your submission and will respond asap'

**Comment by ZiggyAtl** [comment]
@jonathanwburr  (1) yes please make it a required field. (3) yes please use that language (4)  Thank you for taking to time to get in touch with us. We have received your submission and will respond asap, and no longer than 24 hours.

**Comment by ZiggyAtl** [comment]
Thanks for this. Couple of things;
The drop down box looks disproportionately small compared to the other boxes, and the text inside it is smaller too.
Please also update the text on the menu bar at the bottom to say Contact Us.
Please modify the acknowledgement wording to say 'Thanks for getting in touch, we have received your submission and will respond as soon as we can'

**Comment by jonathanwburr** [comment]
@ZiggyAtl made some adjustments. Let me know if that resolves it.  Safari was picking up some default select styles

**Comment by ZiggyAtl** [comment]
Thats great thanks
