### ISSUE TITLE
Bottom navigation bar

### ISSUE THREAD

**Issue by ZiggyAtl** [ocupop/comission-shopify-hydrogen#144]
I've completed some of the things which are needed for the bottom navigation bar, namely the Privacy Policy and Refund Policy (which are in Shopify). The last thing I need to finalize are the terms and conditions.

In looking at the bottom navigation bar, the refund policy is missing from there so that needs adding please. Could we tidy up the items in there so they are ordered logically for whoever is looking at it please (under column headings). It would also be useful, as it creates a structure for where things would go when we start adding them (e.g. blog, testimonials etc). I've attached a file showing the columns and order.
[Bottom navigation menu.xlsx](https://github.com/ocupop/comission-shopify-hydrogen/files/9833707/Bottom.navigation.menu.xlsx)

**Comment by paulstroot** [comment]
I have made some updates to the layout of the bottom navigation bar.

Content for these pages can be entered in the Shopify admin under "Online Store -> pages". I'm assigning this task to you now @ZiggyAtl for you to enter in that text. let us know if you need any assistance in styling the bodycopy.

**Comment by ZiggyAtl** [comment]
I entered a comment in here but it seems to have disappeared, so entering again. Sorry if you get it twice.

@paulstroot thanks for that. Just have a couple of questions for things I don't know how to address. The item in the bottom navigation bar which says Partners Overview should say Museum Overview and should link to the page which used to be referred to as For Museums (which I now can't find).

In terms of the Privacy Policy and Returns Policy, is the system designed to grab the wording which I have previously created in Shopify for these policies, or do I need to copy and paste from one box to another? There's currently nothing showing on the website, so I wasn't sure if it was missing a link or whether I needed to copy and paste.

**Comment by paulstroot** [comment]
Thanks. I'm updating that footer link now.

For the Privacy Policy and Returns policy content, I was actually little late to this conversation, so I didn't actually know all of the details until you explained your issue above. I just did a little research and understand the disconnect now, so thanks for that.

I realize now that the place where you have entered the information in the Shopify Admin is a different place where the content was being drawn in for the pages. I think I can make an update so that you can enter the info just once where you have it now, and it will display properly when the link is clicked in the footer.

**Comment by ZiggyAtl** [comment]
@paulstroot that's great. So if I ever modify the terms and conditions in the future, I just need to update in the Admin section in Spotify and it will automatically update the website.

**Comment by paulstroot** [comment]
Correct. I just pushed this update to [https://store.comission.art](https://store.comission.art/) for review
#147
