### ISSUE TITLE
Need Jobs, Privacy, Terms and Conditions page content

### ISSUE THREAD

**Issue by jonathanwburr** [ocupop/comission-shopify-hydrogen#7]

**Comment by tbeck** [comment]
@ZiggyAtl - Just flagging you on this issue for visibility.

**Comment by paulstroot** [comment]
Privacy and Refund policy have been added. Just need to add Terms and Conditions

You can edit this content in Shopify under "Settings -> Policies"

**Comment by ZiggyAtl** [comment]
@paulstroot I've added the Terms and Conditions now. One thing I then wanted to check was that the system required people to click their acceptance of the Terms and the Privacy Policy before they could purchase anything. Unfortunately I've lost those details you gave me to do sample orders so I couldn't check it. Does the system require their acceptance of the terms? And please can you resend me the info to process sample orders. Thanks

**Comment by jonathanwburr** [comment]
Disable checkout button until terms and conditions and privacy policy have been agreed (checkbox)

**Comment by ZiggyAtl** [comment]
@paulstroot when I was putting together the Terms and Conditions, I needed to include a link to the Privacy Policy. As it is a pop up and not a separate webpage I reached out to find out what to use and you said to use /policies/refund-policy

Unfortunately that didn't work and rather than a link appearing, the text appears. Please see below for an example. Did I do something wrong?

SECTION 5 - PRODUCTS OR SERVICES (if applicable)
Certain products or Services may be available exclusively online through the website. These products or Services may have limited quantities and are subject to return or exchange only according to our Returns Policy [/policies/refund-policy]. We have made every effort to display as accurately as possible the colors and images of our products that appear at the store.

**Comment by ZiggyAtl** [comment]
@paulstroot I currently don't have any content for the Jobs page, but may do in the near future. Is this page anything like the Terms and Conditions and Privacy pages, where I can just enter the text and it will update on the site? And if so where do I go to access that please?

**Comment by jonathanwburr** [comment]
@ZiggyAtl re:links to other policy pages, i believe i was able to resolve these. In the editor I highlighted the text I wanted to link from, clicked the link icon, and entered the links.
Re: user agreement to terms, I've added a checkbox that needs to be checked before they can click to check out

**Comment by ZiggyAtl** [comment]
@jonathanwburr thanks for that, it all looks good. Are you able to answer the question I asked Paul above? 

Is the Jobs page like the Terms and Conditions and Privacy pages, where there is somewhere I can enter the text and it will update on the site? And if so where do I go to access that please?

**Comment by jonathanwburr** [comment]
@ZiggyAtl I've added a jobs page that you should be able to edit. https://comission-art.myshopify.com/admin/pages/94598037683
I will need to add it to the navigation once you have content populated

**Comment by ZiggyAtl** [comment]
@paulstroot thank you. As there's already a Jobs page in the navigation could you use that? Also that page is currently blank anyway, so it won't matter that there's no content in the one on Shopify.

Wondering how that page works. Will every time I create a new job it adds to the rest of them on that page? And if I delete one it will take just that one off?

**Comment by jonathanwburr** [comment]
Yes we can use that link. 
I put up an example of how you might use the page to add multiple Jobs. The 'Title' field is the page title, and then you could use typography (I used h2 size headings) to create multiple listings on the page and put up as many or as few as you like

**Comment by ZiggyAtl** [comment]
@paulstroot that works. Please can you now link it to the existing page. I've added some content in the Shopify admin so at least it won't be a blank page
