### ISSUE TITLE
Login flow issues

### ISSUE THREAD

**Issue by tbeck** [ocupop/comission-shopify-hydrogen#96]
I tried adding this one to the issues but couldn't. Also this issue may be covered elsewhere, so if it is please ignore this message and close the issue. I selected a DAB while I was not logged in, then selected the checkout option, but it goes to this screen and I thought it should go to a custom CoM log in page?
![Screen Shot 2022-09-20 at 9 20 15 PM](https://user-images.githubusercontent.com/112654923/191393975-67abfcad-9d51-4095-9281-b84f8b0dd832.png)

_Originally posted by @ZiggyAtl in https://github.com/ocupop/comission-shopify-hydrogen/issues/53#issuecomment-1253095878_

**Comment by jonathanwburr** [comment]
Issue was recreated in safari, need to debug why shopify hosted page redirect doesn't work

**Comment by jonathanwburr** [comment]
@ZiggyAtl Adjusted configuration settings in shopify and seems to be resolving correctly on our end. Test and let us know

**Comment by ZiggyAtl** [comment]
It's now taking me to a CoM page and not a Shopify one. However it takes me to a screen where I can check out without creating an account. I thought it was a requirement to have an account to be able to buy a DAB, otherwise how can people log in later and view their collections? Shouldn't it be a requirement that they have to create their account first?

Also, once I get to the checkout I can't update the items in my cart. I realized there was already a DAB in there from the last time I had visited, and as a user I would then have wanted to delete one. However it doesn't allow me to delete anything that's in the cart, and I think it should be able to do that.

**Comment by tbeck** [comment]
Hi @ZiggyAtl
- created a new issue to track remove from cart functionality: #126 
- create a new issue to track Back Link from checkout page: #127

RE: Account creation... While customers can perform checkout before creating an account, they will be required to create the account in order to view/download certificates. It follows this process:

1. Visitor adds to cart
2. Checkout (email is captured)
3. Order confirmation is sent and includes links to download cert etc.
4. User clicks link and is directed to Login/Signup
5. If "Signup" then order details are assigned to new account after creation.

This flow makes the purchase frictionless and gives the user a clear path to account creation.

I am happy to talk it through and provide any additional context if needed.

**Comment by ZiggyAtl** [comment]
That makes sense. Best of both worlds. Fewer steps to buy a product, but they still need to set up an account to use it.
